# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Function Deployments

on:
  push:
    branches:
      - dan
    paths:
      - 'Functions/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: self-hosted
    steps:
      - name: 'Checkout GitHub Action'
      - uses: actions/checkout@v3
      
      - run: |
          git show --name-only

      - name: 'Show Environment'
        run: |
          dir env:
          ("The Change is in {0}" -f $env:commitmsg.split(" ")[0])
        shell: pwsh