# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Powershell project to Azure Function App - trigpunchub

on:
  push:
    branches:
      - main
    paths:
      - 'Functions/trigpunchhub/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './Functions/trigpunchhub' # set this to the path to your web app project, defaults to the repository root

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Run Az Login'
        shell: PowerShell
        run: |
          Connect-AzAccount -Identity
          $token = (Get-AzAccessToken).token

      - name: 'Custom Kudu'
        shell: PowerShell
        run: |
          try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { }
          try { $token = (Get-AzAccessToken).token } catch { }
          if ($token) {
            $userAgent = 'powershell/1.0'
            $urlzip = 'https://trigpunchub.scm.azurewebsites.net/zipdeploy'
            $applocation = "C:\actions-runner\_work\pushazfunctest\pushazfunctest\Functions\trigpunchhub"
            Write-Output $applocation
            [System.IO.Compression.ZipFile]::CreateFromDirectory($applocation,'C:\actions-runner\_work\_temp\pushazfunctest.zip')
            $invoke_params = @{
              Uri = $urlzip 
              Headers = @{Authorization="Bearer $token"} 
              UserAgent = $userAgent 
              Method PUT 
              InFile "C:\actions-runner\_work\_temp\pushazfunctest.zip" 
              ContentType = "multipart/form-data"
            }
            try { Invoke-WebRequest  -Verbose -UseBasicParsing }
            catch { $_ }
          }
