# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Functions

on:
  push:
    branches:
      - main
    paths:
      - 'Functions/**'

jobs:
  publish_functions:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: self-hosted
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: 'File Differences'
        run: |
          git show --name-only

      - name: 'Show Environment'
        run: |
          dir env:
          ("The Change is in {0}" -f $env:commitmsg.split(" ")[0])
        shell: pwsh

      - name: 'Run Az Login'
        shell: pwsh
        run: |
          Connect-AzAccount -Identity
          #$token = (Get-AzAccessToken).token

      - name: 'Custom Kudu'
        shell: pwsh
        run: |
          try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { }
          try { $token = (Get-AzAccessToken).token } catch { }
          if ($token) {
            $functionApp = $env:commitmsg.split(" ")[0]
            $functionURL = [string]::concat('https://',$functionApp,'.scm.azurewebsites.net/zipdeploy')
            $urlzip = $functionURL
            $applocation = [string]::concat($env:GITHUB_WORKSPACE,'\','Functions\',$functionApp)
            Write-Output $applocation
            $zipOutput = [string]::concat($env:RUNNER_TEMP,'\',$functionApp,'.zip')
            [System.IO.Compression.ZipFile]::CreateFromDirectory($applocation,$zipOutput)
            $invoke_params = @{
              Uri = $urlzip 
              Headers = @{Authorization="Bearer $token"} 
              UserAgent = 'powershell/1.0'
              Method = 'PUT'
              InFile = $zipOutput 
              ContentType = "multipart/form-data"
            }
            try { Invoke-WebRequest @invoke_params -Verbose -UseBasicParsing }
            catch { $_ }
          }
